apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3
  storage:
    storageClass: longhorn-strict-local
    size: 10Gi
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  managed:
    roles:
    - name: concourse
      login: true
      passwordSecret:
        name: concourse-password
