apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3
  storage:
    storageClass: longhorn-strict-local
    size: 10Gi
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  probes:
    startup:
      periodSeconds: 30
      timeoutSeconds: 5
    readiness:
      periodSeconds: 30
      timeoutSeconds: 5
    liveness:
      periodSeconds: 30
      timeoutSeconds: 5
      isolationCheck:
        requestTimeout: 5000
        connectionTimeout: 5000
  managed:
    roles:
    - name: concourse
      login: true
      passwordSecret:
        name: concourse-password
