---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: concourse-password
  namespace: postgres
spec:
  encryptedData:
    password: AgDZzu3hVhxIkz1L3BzcxNdNlDOvB1sM5KmPftbMKl2sTTXaIQB6pubhYjR9rKR1bU9sDYcxPZZdNGr8TmgwuktOfrRKoc3QmfwWXPm8XkE2B6g7iXSeoAcxoZ9FzzPCI1ClGQrzr9ZpioouxkMaGJupwWFDiyDySh8JKxkACMOOaetH2XaEI/zE6tXWxrRY7cHx3Ef9IRU7IYDVKMiDtJ1tsaiSFFjly1KBEkPYkhWGD1d8mhfTtlKBE5Xu5nDUy2wPT7e2JpTa1hETLnlzVcKLz0g4JqOtFq62s66AEA/IQeeAi/7buNfaH0CUvUqXVUqiRqt5Bk7/TX5m8Sn9a07Iw7pPWUcHfWQaMdIsM4obwTN16Wd1SuEhUYppBHSzJpCW+v/DlydMti8tzBGiL7/d3ZI5V1yUz6erS2NMSLfrY5s0B8V1WUaxuB7ZonsveFljF2J1oR7CKenrhS4L0qzp5Nd7EBjewwZgWs8aicXxZgJ9Qyv5jbEwdoeuz5nyxSv4bd4URdOMNqjttWcmylAwkGyxila4LdtJGtu3oVRYJG1N2hFV1K+TVgz2G1IjTP7LOsGNyirheH2fZxh/cEH5HPLbOo1kK7WnNcyJvAIGMtPUEqYtxVaYZDsF5G/WdbWp/H9xUSkC3LsHQIjNQeJ7qKoliqyTlIu3Tjv6biJAiLPnynNJPX00wZqjgwoZqPRhY9Oa9ZNJU1H7m18iPRwwUkyzFle9s869IP9SgObSn+zbJ8sjgcQqqlGHz6iZ46Q=
    username: AgAO3JrW0azNY+WLsexsFv1YbWIvpvFjSjULms2/a03V0gl9bwzbVHTuhrdrA3Te30Go1+Fh3zJEowR4Q9pNdyKaNlJy0gmvgTDKGPX9W0Jp59ai147v+tZgpv0ycfUstO9XIFRkC17gK3RSbDVhg6gXCIOrvtOhT7zwuaBNN9SFwXDUt3UbvgLR5orRIti3fC+FNneRif9O5MdI3na1juKL8i3CcHO5Hfopq7h4Vv6F8ugDydTmo6wH4WM5ZF3E2k1leb6qWMWVnaC8XRW6SXiyFK9DA48aMg9YRLxlke7rsuFg/L3koiPpjxActfy+z2GJoaVmPHEIGknx2XdrT4lHk8of+ADqSs+UHSDDGHP81CJWauau/Nb7aMuost3GWRT/CnLU0TuYTQQTL1IFKMHfNDe/9/zZLOM+UhNs3ngd1xzrnL5mfTZ9HZadqGR3UQqFpQfdevl2aVs8RjXJ5Swqu9YW6ZXMOv/OD6R4xmGN1YAZQHYajp9dcPB16vR4YTcV1tM9YfWwbZHs0StJfQIZ9ln21EK+j/XdP1EeKIj77AcwM7e8lxMPuDYWzAeStN+e66iVdA3hAFXNPq63s5D37lT8XKtaHfMA6b4JMNw4rECybVwM5/AEA8A5e5mdqG1WT1NEh9RkXmVwbGV1jV/boVPwkTPMEpb8gokPjNZFoBr/X8oGpgKd8puuTpBYjzi4IFGdoYivFRs=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: concourse-password
      namespace: postgres
    type: kubernetes.io/basic-auth
