hostname: &hostname home.ncraig.dev
tlsSecretName: home-ncraig-dev-cert

oauth2-proxy:
  config:
    existingSecret: homepage-oauth-secret
    configFile: |
      provider = "oidc"
      email_domains = "*"
      oidc_email_claim = "sub"
      upstreams = "file:///dev/null"
      oidc_issuer_url = "https://sso.ncraig.dev/oauth2/openid/homepage"
      code_challenge_method = "S256"
  ingress:
    enabled: true
    className: nginx
    hosts:
    - *hostname
    path: /oauth2
    pathType: Prefix
