apiVersion: v1
kind: Service
metadata:
  name: lldap-external
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 389
      targetPort: ldap
      protocol: TCP
      name: ldap
  selector:
    {{- include "lldap.selectorLabels" . | nindent 4 }}
