apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: ldap
      protocol: TCP
      name: ldap
  selector:
    {{- include "lldap.selectorLabels" . | nindent 4 }}
