apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lldap-data-pv
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
