---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-keys
  namespace: crowdsec
spec:
  encryptedData:
    BOUNCER_KEY_traefik: AgB19du+J3eMyO2rwE8V0XdSsyjdqcfiZ72fI7ZtiSoL3xQIK3hqMwi8GUNZYxlljO/QKedKdyiKfG47b20OyyaJMxJSFMVBnKtUMbKPslOvjbJkrjykEZDv/ISMKmetYnlu5OLCwiK8b6I5xIjjYk4scYu6NSVtEnTYpY5TfkNk1h7VeQcQMHSzDBwwb9aECurcICdNKVi56vaqLnhP/woJtYi/5Z4nF8d0qMP4Ie7J+bFIcGHTVNTDloENnCmIvOXfmCklkkP24g5omOHeln8OUsOVUVdgOcBjefRYNDkjuifTcPZnxnR6KAK6Jlrbi8ITqFkOLnPA5GaiCtUDgIcH6JIQ3thEqLiy5Wcwxno3UA3umo3rLXImLzJgHG8alWTN87FZYbTgepNUPWJ6nFC7xuIxznGMUwt6yHoRn7JuJJW8exY0PAT1K8jbfvkOoF2RLnIuF1eifnm9OzP2jMs/CjWjAZ3bN8J6tJwjTtCNhkIbwhHvWDC77MPDa/smJU/W84KMG+5i6hlrel3WWyimMiVxnidA1G+ycz5IjXM7MITDbGgm8V1qBYjM1CxpMZVFXFODKyI2QZJ91nKtwGgsgSwCyLJMMwmhO+XYiL/qK5qnufcZNpcUYQpTooN27ocOywzptDiaa40Epr3zvaqC61cxNjQLznU7zDZ5TByau+4jtQsF27ofLqjDHMyQczYZrja70IEFPbc3mwxycky/C5ZRkiyn6YvBCt693kfelRKviRX0riAr1begbY4CpiU=
    ENROLL_KEY: AgADfq8RlN37zdEePHvIelLhgJBS3k/gH3j/f8f0hKyfGQVIjrB0ciygGIfjmp54HQ8xecmK3fPeJiK1OeQqpLC+ZnmPvglinRccsFiydLL44ClteIo6B9nF1A4Ij856EnfSjJAsW7Zzp6ZHPxKSQCdfeCE/8irfywkDQA1OfMORkUIczb4LidimM6wtuoGZ1PquklBYnXpA3fbXFa3xF5gWnsSRSwWzmcwUCPIglPEWWWLkIN9VgJBhxLM9WUrMjaEiYm9YVXxoJb2qHx0f9pepZZzzPXPgqcBccynilb6T4DKHRAlOS5PymQzBVAJTF7Z6BwJ0C3icHqsm0HK2JWCCWB6UKx3n3Y1qo/t/cN37NAN80My0A4WNSEDLMh07Bt2diO0/B4nw8taWSfP/8ro6tn6rHTv1aucE5engTobuwn84E8F2jDXw2xJ6j3rjhT6LMTr1pOaoKXIsYsrp0xrK1Iqfslu5XCTpkQ6x9+U9E+f0gJ+TzyzFOyDpb7PSdtGoYxRN0qZt72kqU3F3FFLC39wkP2UsJAocalLFXv7sq7JeOIApIXWqfgkLhaoPg3SfmB7G3PjxzwDD8fv51q4PYHN3sbooJpxZqf7AQHt5aM/GiBsiiYw6VFFFJPKKZ+dExcPA8svBVDYY6SsAvv4x+ljhpEhfhejK6wQchtOPhbrj2w6skuoUQcO8aHL1lZRUXNfK5UgqWLTgyWJbhi+4upPrYnuzub/b
  template:
    metadata:
      name: crowdsec-keys
      namespace: crowdsec
    type: Opaque
