---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secret
  namespace: crowdsec
spec:
  encryptedData:
    password: AgCFLYw9zOKJ+G/07jL7vrjr0Y34zbRPI1oarWWx0AO5hyCE1RaisK0MVgT1C3hxJzcbSMtaSt9ARN+LHW/fdF8m5Ae4RtiUapetp2Ug1RRdCp8LFAe964V6ETaa0FrKlpsaWdbseeVFxEj0dXhLsH1unVAQZv4Hbp3pz/w5EVA56JlB+waCkzd6CnSHGlYiii4EiplcaczrpuuRoTb373PrxslU+XPmjZOh7ntlbtXeVGpo5d6huedC8ndQlryuV8JyEUFuQjb/a/Zo88WZ+S25jjJ1gm/VAI6269dpUtrfh3yPT+xssSj36s5VKxSQTejZMhRgPYbC0rtt5OzrStYjPUOs4qRlmR0hz+kL5QlkzdCgOVRU+CF65ZQo5nwdSGwgs+d+qWUZpTSDctTG5ReLlfDPdiuHi0gOMKay4zUCwOyb0D1y1O3GoCmLCh8vmy7Oz7PL7EwAd1ZTepHCMZCbsc8b1z25sJ8NvmR7MuLs/XE5X75ZxpNDQGRE2Dh6vcndGfW3a3iWHW+PbtOtOf6zF4dG5A1zW/ty1JrnjNm1P1DlM6Wiv/JziKdWojJ7SPFzrQMSmD7Zu7Sd2CXo3Wrz/1BbI8Ca2o5oMIub7yp9zQZ7rSelH3xyevptFN+WqEBT9tH5qjPWotuZ++3GhilrqflVEYYCuyadlB/sKvtRmuNOnztCDe+i8qIOQYOPL4AE+8N96W3TMQWSaUoPwRYGuo2lEsfaJ0YsEmcipGHcOFceugHVY3hN79D6JsABv0M=
  template:
    metadata:
      name: mariadb-secret
      namespace: crowdsec
