apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: forgejo
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: forgejo
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  passwordSecretKeyRef:
    name: mariadb-secret
    key: password
  host: "%"
  cleanupPolicy: Delete
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: forgejo
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  privileges:
    - "ALL"
  database: forgejo
  table: "*"
  username: forgejo
  host: "%"
