---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: forgejo
spec:
  encryptedData:
    password: AgBAk4K8xkrQiI3U5Pa6ds5+lxN8eHRZQ2v6MhsO0dw5yoUazPvaA8WzLAHCryopTujbLFOTepP7HOeXPByXLgwgvnkDLByUI/3+Iw9xf8p3FZv8R2vVHNu0caeFuYlxxBh3Pi9N7lNUjCZMvSeTQiMaIqGr8fmMlQyUgvSata3X8koSS/LrfSN2n7jhHQwdrL2qvdgixpC3Tq1OPazOu4d2nZCMmnUqloLffmpmsrqmdwG1aLUsIOStUsgZ8cESlrxi1NsOOFs82MxdKLyl0mj5OtFKau7T1HoqUIimPAtQRgaXVga4sCDDROJ5BpDkPzTvvzhEscWzrc2jR0KM4T1sCwrymNTXoPr10BIhtRyffXqJd+zr0z4fwkSQzDSVRP1iviXXL1w5vcSlJsNi9NW2YIw6jzCyB2TwjqtXYevy/SIKNLPYcprCuOHsg6qj8DvzHtaTqA1bXBoQkRtUIVoQ6eFAsXvV8ijIn0I4KIaPja9IwZbRZCyXijFQjuItQdmhVERay1uMTsaG/t1R2y2mZqrwYHtYF/hDkdHjTM6EcK5XenoQLM069Y7LB8l9VALSmzt+gyGt37w6BNN18Gyj1bH4KuT1R14YPPfTiITJRvdr3c/grnJ2dOgFO3fn0NHp0mWztQn9fe8LbM+8eddK/AkPR8nGZGMV4O03e75S658mnOahKs081atpx+hXaOZX4ejXCBqWw9olUqw4zJWt+wSx3HICLzhEm8rFUW0BJ/z38gn2qS5dAvf+xFdXF1I=
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-secret
      namespace: forgejo
