---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: valkey-secret
  namespace: forgejo
spec:
  encryptedData:
    valkey-connection-str: AgBw22AqdJN6l+/sK61JzAbdkeMwmMWsS6qQKr9FiZgUwO8ycHIxGAop3GM9y9FLkFlYlpbkVNqveF1ee8HuVJQV2LaVj3NE7UGvtj3xxGrHl4wlwJE5JejUIAQIfGIQss491k/1D3T5WpD0rBr4HTKLrbYcB7BP68yArXrrbhwRSaUudpr1wt2Qk+HbBttKaQR5c2sjGdQ7YQR9JQoZgUht6lsdWhrrI9ws9onU3hapZxXogHDckcLRsByPR8WZzQGs1lbdfTGKHKMMVzVKw2cJkKYR2Sv7vHXY9PCmneFHuaCDp/J11v1ucg4h4q4HHDTrZ4/fy6ObFTQy9DavpCjJNDMuYsn3VNFz9y8+Td/sArJ1uPCR/ZXyvth0rfQVF19gm6I2D/sNxGsqn8HudhemG3uXcJ6lMpLjhcURWtao0XuCVg78PZWEzlbB8Z6a2PY3IkHHtWpJxQR4ZXHDR3hiVuldXZhreqCJS4V+EV9OoATlOJy2WbxtltYgYQ1pgSpurmADWwVXlibNaGkGMuIYpT33d8vSrvRoybDisnmZWyQGNt+s7zH/TRkKMpzN7cDnnz+bp25cqmLFbSu7gwt5MV4aPZONrd27Sy207a19wUEpxv2BRTbY+VyRVHTDWrPHT2St32x4agGXpBnZ7keObte2c6LDAw/PCg44Qrkc7KHgZQHKhg5ZH4Dos9El74SPGQ78fa62CuUc9iDUfkeY9OingpDeN83DhaMLTw+n/r6uZ3IWy5PO09t+flWc8UIQGMhrDV9BSF6KjXw0CFvNE92O9docPacwO3R9Fzd0/N/miM/HgiwuNbEfTI/ZsSlKvhYHF48=
    valkey-password: AgBGrXh7SQ11cZtPxi1qhx4aAaKmVnsYT0cyYHBjlzxiS+/Wb4DmppFhi1Xclf0f9oegJoCMzlEIRPY28nqbB3PXJjPPiltrG3BdvOIYYoq+1gXFLJsA2IJfcucVtDJdRIwvgyJEC0FUYNuSaadEutMAhDJYv/F3IJgwuEsY+nBOcsnCbKOpC6jgv8hA8aZ/qbdMjIVRqGNGrNCaCr0IIphttHofTQkYbxHu1/iw68YhfNgHCwNCb3gRtMTEtRs1N/KzffR9EL+WjUVcYZOJmdc8ZKE0Wa7oLKPGCXj5QntwogSygznMMoEI4njReqH8v19J76zKNRlkmr+oLtNynvqyoMmYB9mpfRJkw+HuhJ2LcxvQL3iyfaNOfLluJBQ0DRKBV0r63RhnbOw4ywnLfAdgssncPYNN4d07tYVz6Mt2ZVaO5s7XSwWTRTFgFH6QcE6EszSO9iebADVZWEGybpC1StSVgvaHQtE57GUJHZBstgu6NTda6ObypWBK35MW4A6FE1PrtTsWVq67QJPI/EISveuUdkv+HmA2OJyoxTK0qHceF2XwOPUfeMRfAbQjxJcV1efhutLKfXL565/izNB7UpdpxUKHt6d6iq9k/e51JECBH+EP3zFU2NiQflfwYUGPzyh40WumHl6kRr75swjl+2GihqD5GMnSRMY+rFdTxAO/xYEgwMazt4NVQvUQmEuL2eKlcjGNjGpymfTjOyyCb/QGhshIYb8zRHaw6mLcxZoe8vp9tRuTa1wXRg==
  template:
    metadata:
      creationTimestamp: null
      name: valkey-secret
      namespace: forgejo
