apiVersion: v2
name: longhorn
version: "0.0.0"
dependencies:
- name: longhorn
  version: "~1.9.0"
  repository: https://charts.longhorn.io
- name: oauth2-proxy
  version: "7.14.1"
  repository: https://oauth2-proxy.github.io/manifests/
