longhorn:
  ingress:
    enabled: true
    ingressClassName: nginx
    host: longhorn.ncraig.dev
    tls: true
    tlsSecret: longhorn-ncraig-dev-cert
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  defaultSettings:
    defaultDataLocality: best-effort
    replicaAutoBalance: least-effort

  # https://github.com/longhorn/longhorn/issues/6415#issuecomment-1802349558
  # https://github.com/longhorn/longhorn/issues/6415#issuecomment-1936996757
  preUpgradeChecker:
    jobEnabled: false
