hostname: &hostname longhorn.ncraig.dev

longhorn:
  ingress:
    enabled: true
    ingressClassName: traefik
    host: *hostname
    tls: true
    tlsSecret: longhorn-ncraig-dev-cert
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: longhorn-oauth2-proxy@kubernetescrd
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Cluster Management
      gethomepage.dev/name: Longhorn
      gethomepage.dev/description: Storage
      gethomepage.dev/icon: sh-rancher-longhorn.svg
      gethomepage.dev/pod-selector: app=longhorn-ui

  defaultSettings:
    defaultDataLocality: best-effort
    replicaAutoBalance: least-effort

  # https://github.com/longhorn/longhorn/issues/6415#issuecomment-1802349558
  # https://github.com/longhorn/longhorn/issues/6415#issuecomment-1936996757
  preUpgradeChecker:
    jobEnabled: false

oauth2-proxy:
  config:
    existingSecret: longhorn-oauth-secret
    configFile: |
      provider = "oidc"
      email_domains = "*"
      oidc_email_claim = "sub"
      upstreams = "file:///dev/null"
      oidc_issuer_url = "https://sso.ncraig.dev/oauth2/openid/longhorn"
      code_challenge_method = "S256"
  ingress:
    enabled: true
    className: traefik
    hosts:
    - *hostname
    path: /oauth2
    pathType: Prefix
