longhorn:
  ingress:
    enabled: true
    ingressClassName: nginx
    host: longhorn.ncraig.dev
    tls: true
    tlsSecret: longhorn-ncraig-dev-cert
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-method: "GET"
      nginx.ingress.kubernetes.io/auth-url: "http://authelia.authelia.svc.cluster.local/api/authz/auth-request"
      nginx.ingress.kubernetes.io/auth-signin: "https://auth.ncraig.dev?rm=$request_method"
      nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Cluster Management
      gethomepage.dev/name: Longhorn
      gethomepage.dev/description: Storage
      gethomepage.dev/icon: sh-rancher-longhorn.svg
      gethomepage.dev/siteMonitor: http://longhorn-frontend.longhorn.svc.cluster.local

  defaultSettings:
    defaultDataLocality: best-effort
    replicaAutoBalance: least-effort

  # https://github.com/longhorn/longhorn/issues/6415#issuecomment-1802349558
  # https://github.com/longhorn/longhorn/issues/6415#issuecomment-1936996757
  preUpgradeChecker:
    jobEnabled: false
