longhorn:
  ingress:
    enabled: true
    ingressClassName: nginx
    host: &hostname longhorn.ncraig.dev
    tls: true
    tlsSecret: longhorn-ncraig-dev-cert
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Cluster Management
      gethomepage.dev/name: Longhorn
      gethomepage.dev/description: Storage
      gethomepage.dev/icon: sh-rancher-longhorn.svg
      gethomepage.dev/pod-selector: app=longhorn-ui

  defaultSettings:
    defaultDataLocality: best-effort
    replicaAutoBalance: least-effort

  # https://github.com/longhorn/longhorn/issues/6415#issuecomment-1802349558
  # https://github.com/longhorn/longhorn/issues/6415#issuecomment-1936996757
  preUpgradeChecker:
    jobEnabled: false

oauth2-proxy:
  config:
    existingSecret: longhorn-oauth-secret
    configFile: |
      provider = "oidc"
      email_domains = "*"
      oidc_email_claim = "sub"
      upstreams = "file:///dev/null"
      oidc_issuer_url = "https://sso.ncraig.dev/oauth2/openid/longhorn"
      code_challenge_method = "S256"
  ingress:
    enabled: true
    className: nginx
    hosts:
    - *hostname
    path: /oauth2
    pathType: Prefix
