apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
