apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sso-ncraig-dev-cert
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
spec:
  secretName: sso-ncraig-dev-cert
  dnsNames:
  - sso.ncraig.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
