apiVersion: v1
kind: ConfigMap
metadata:
  name: kanidm
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
data:
  server.toml: |
    version = "2"
    bindaddress = "0.0.0.0:8443"
    ldapbindaddress = "0.0.0.0:3636"
    db_path = "/db/kanidm.db"

    tls_chain = "/cert/tls.crt"
    tls_key = "/cert/tls.key"

    domain = "{{ .Values.domain }}"
    origin = "https://{{ .Values.domain }}:443"

    [http_client_address_info]
    x-forward-for = ["10.0.0.0/8"]
