apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanidm
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .Values.tls_secret }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kanidm
                port:
                  number: 443
