apiVersion: v1
kind: Service
metadata:
  name: kanidm-ldap
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 636
      targetPort: ldap
      protocol: TCP
      name: ldap
  selector:
    {{- include "kanidm.selectorLabels" . | nindent 4 }}
