apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
