---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-env-secret
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgBadynMW7F9zjQLtyrzVAXpTrUKlXLmPH9V8DiogwmtfsfU4ffSH5uYO4VpnCb416QpJjZw38wrC2LFxy/R8s7FpL9xDz1omxvtFFQvvpPjjj/7X2TobI84tfY29mD9kxYtTps/RJOMx+kOHdQhU/gVHfCrHae+sBSEmEZunOpLKMLSKxp7o7iAaYfAMZBe6D1AeSlsGBVOyGV7Hzg1SE95n6RarmLpIulX1vXSftANOQnoMu0uQWV5WbSrvXNuuLfrPBnuXh3SPiIMd+fN2Wds3nB5C/lT0Enq1WSennDYSHjGK8R6LkvuQlWbYdwKoKdWQWrg7mIFuqFMLkWf/qZfZ1fMWKlSiuxcLswlHk+2hvFvFIrvTDRI8x9xhHhoQvlpY+mYZLEtjgmcnDtn65+qGdwOHKYlVPgJLzDMgtiFQ6Eatiyyqvd03CthV/Q6jz7WNyntC++RZuOiNBbyIMYb+CiJp+Gt9tvI4i+tM7a1DLlCXkYGFGRldsozmyEnPe9YFo9ovnYlardgM8R7wAPjqsN+uOO7QWWkLg4WcqVfDOUv6Dy/vZK5bUF+/7bZ2woseeE/Bj4ELVRPol9MSw/LUJYtKXTE+PNOlEKs8kfOuQUgX/Os6PSoEv4BGPEXFIr6F4TuX4cPjsWmw9ZXB0iBpcyPDEgxIZHcW+TzEkSw4KmwiKItSuG8aMhVqRHPMbB0DKG0l6uxUi5o2ds/1L0Z7VihYMMFHQhd0tvuQVmYSzR25m9un4FZ
    RENOVATE_TOKEN: AgB5K9FiR4ipPvWeIpZPu3NbN+/oKruGwUNFNG2HEcdii1muPjVi/i1GZAWHlf7PIpTTs75M/K+MRpObChXGPZ9TnzDho5yHZ+Zsd51Yj4ULCh+BqmKr+eKvPDJk2ZBuIlt0l1ZCv26V7KMOqBnCYohleTl9XIC6reyaqEUh+cyaHT88ggo78uvkR3JTodpCp58P7B3mH50g7+G/9SPYjB6hbIdZG1bNjpOpKi2ECtwNOH7dvvkQqgPBVnhCK2kxK31/MCRGiKRRGb/Q1aQGBw1MqSU2fmaFzc29GEF0XGRTh5+pW9JZNUGAB8oF15G+GY0WZJ8nBApOXAHvJjwxq0sEvJoVEiZ682TNb6QfobxfM8vYiOJZNzZpfDIwg6IdSnvAIde8+/WPZQjELt6w89NEewACkdHXwEBzjoc8KdIMmcyklA9M0mJNtLolvAlwSt2lWbneLrRMb+BMWHsL57SCMbI2m2r0zlJIa8Ndxeo9iCypM3DnvzcB5ASw4thlozki2RJsA80HmhbHtLeokhHXjF4k0XrXl08Cl5kxeaUJEcK0RHOVNDY7z9DF/lznXpoBzWGK4R1ckzsCnkBxPkQHfzn8OTMjCqfhw3TcYnqkayRJgeZSgWHjlEXGxAceHkbJ+A5tjEscIh1J+Z9rRB2Pv1n3rX7nhSq9jpC55thChQUC/EL2OT54tzdSHhYJTibbzR/oVzbonZ19gZIG4VCe+rUwYodjauOx1BHKotn/2q3TNRdKa85+
  template:
    metadata:
      creationTimestamp: null
      name: renovate-env-secret
      namespace: renovate
