apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
