apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "syncthing.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "syncthing.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: syncthing
          image: "syncthing/syncthing:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8384
              protocol: TCP
            - containerPort: 22000
              protocol: TCP
            - containerPort: 22000
              protocol: UDP
            - containerPort: 21027
              protocol: UDP
          volumeMounts:
            - mountPath: /var/syncthing
              name: syncthing-config
            - mountPath: /opt/syncthing
              name: syncthing-data
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ALL]
      volumes:
      - name: syncthing-data
        persistentVolumeClaim:
          claimName: syncthing-data
      - name: syncthing-config
        persistentVolumeClaim:
          claimName: syncthing-config
