apiVersion: v1
kind: Service
metadata:
  name: syncthing-http
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
