apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-oauth2-proxy@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Services
    gethomepage.dev/name: Syncthing
    gethomepage.dev/description: File Synchronization Server
    gethomepage.dev/icon: sh-syncthing.svg
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - syncthing.ncraig.dev
      secretName: syncthing-ncraig-dev-cert
  rules:
    - host: syncthing.ncraig.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: syncthing-http
                port:
                  number: 80
