apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-method: 'GET'
    nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local/api/authz/auth-request'
    nginx.ingress.kubernetes.io/auth-signin: 'https://auth.ncraig.dev?rm=$request_method'
    nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Services
    gethomepage.dev/name: Syncthing
    gethomepage.dev/description: File Synchronization Server
    gethomepage.dev/icon: sh-syncthing.svg
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - syncthing.ncraig.dev
      secretName: syncthing-ncraig-dev-cert
  rules:
    - host: syncthing.ncraig.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: syncthing-http
                port:
                  number: 80
