apiVersion: v1
kind: Service
metadata:
  name: syncthing-transfer
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 22000
      protocol: TCP
      name: tcp-transfer
    - port: 22000
      protocol: UDP
      name: quic-transfer
    - port: 21027
      protocol: UDP
      name: local-discovery
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
