apiVersion: v2
name: loki
version: "0.0.0"
dependencies:
- name: "loki"
  repository: "https://grafana-community.github.io/helm-charts"
  version: "18.5.1"
- name: "alloy"
  repository: "https://grafana.github.io/helm-charts"
  version: "1.10.1"
