apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-webhook-relay-config
data:
  webhook_relay.conf.template: |
    server {
      listen 1234;

      location / {
        proxy_pass ${DISCORD_WEBHOOK_URL};
      }
    }
