---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook-url
  namespace: prometheus
spec:
  encryptedData:
    DISCORD_WEBHOOK_URL: AgCSx3uoqoX0HbGKlvZp69wG5T4gZNk725ML0j7h48FBPhtG5Cp0a0lY6KkdM5F4td5IklnRiVkir0gf/R5/80HWs+/zSoUvdUfttTmSAAo2Md4JPglNBVLEwLGzaxxfRYqKm3dIxWsQba89pe+dWAL85rBhBxwsymPlq2/w7IXimULLCPYQThOSqB/WD0hAjuE74ChJVFqrNJ5h7w6mudDlDRTwwhEby2kk2SzYYNIXCGhcIUTrGoAdUQEhCHkjM1YajI0b4ztNVBAxb3y+QrUEBUAr9n7xb31K1t+gakyJ4tEswC3MowZPJFQECK7YeYA99qabv/EiPqPHTOl6K4L+2mYeSBVl+zyhIsrkxQq1MqiEASSHUCnBB2qA8jfAmCD/iosqk9bUpb6pkkTRVZFohT+clVMPrKnY/HUjlB/H+NIdSQCQnI4LHqBbb0kbMUwChSzk1ZZNCfxZOKfXvQfI0I3WvQbqOL72gIgpzA9s73l9BE/ZfyWMToWG4j1TjeMlZ4a6q1RRviJoUprCJvap1A6a6LPph+OtlE2dzk5ekgIPindBKIAUkNxwT9TBVjeW48TmwilHmYAJUrAyt9AZbg1o5Sq9d9Hbs5+GGnCoxjDmVZFzRmcqoUg8jSQEcUlp469nyajQHNaUGFrjhYnYpHI78yl7rH7xjyTl7+6cvGRu4TFcx70y6zikVLEiT+ncsXdSn1D+ETDba7+vbpfj2eyn4RHJRcQUcnlSzD7ziZeceu3+8iSU5UoW/npvVwvWviuk6RxBVp+N/eX0IHATVZUxmix5e6ux3hrE/mxAh6WwS5jSrfqR1fpc2pMUmwKG5g7WP9M7ockyDWcnmmyeUe0AQ0jgdY5w
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook-url
      namespace: prometheus
