apiVersion: batch/v1
kind: CronJob
metadata:
  name: mirror-garage
spec:
  schedule: "30 15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          restartPolicy: Never
          containers:
          - name: mirror-garage
            image: git.ncraig.dev/noahc/mirror-helm:latest
            env:
            - name: SOURCE
              value: https://git.deuxfleurs.fr/api/v1/repos/Deuxfleurs/garage/releases
            - name: CHART_SUBPATH
              value: garage/script/helm/garage
            - name: DEST
              value: https://git.ncraig.dev/api/packages/noahc/helm/api/charts
            envFrom:
            - secretRef:
                name: mirror-garage-secret
            volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /opt
              name: persist
            securityContext:
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop: [ALL]
          volumes:
          - name: tmp
            emptyDir: {}
          - name: persist
            persistentVolumeClaim:
              claimName: mirror-garage
          - name: scripts
            configMap:
              name: mirror-garage
