---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mirror-garage-secret
  namespace: misc
spec:
  encryptedData:
    PASSWORD: AgAgUmU57NcLgaZbgZgbAJ58UtjrjuwaZd6fZUK+Y1MRA62Xtlx0LqQVypSFb50rV6Kob3zRVwZaUFyXxzE63WsJVKvA4noZipcEnmirJPb6EVqQp3ZkEXWuqwPbH3EO1uUzzy7sZFvQNrUNbZfkXN4S1wSNO9xWa1ETNjLWyWIxGkRT5hrmwY7X0Wy47Dz3nGfGjRbm+VEfjkUpmuhJieOwGAc2/5DTtl+Iug1ZxiGbqH/D+3DZn4DDXN5gQ8zY6n9yuslY372/BBaa1Cu2S0KPVmdL3Zk7/nYxlCCOElGzrCRoiR0sM1GCukqhR+7BeZnIZMPpVCTk8xFDg/b2bHxnbQbxPVY/LycEO2XB7gqQQQkWTfByLnMdxys2MED87ipdqoF1nvIDihaywNiepQrQfWAD/9Dc0XN7bQvmPdrVySKhkpJK91t769X//iyjgNqDb/ZwwgWOzl8/++pA1t/FJkzs1OwBjz7LBrdhQErnlywJsZBs4dz5ZIWy+f9PrbfhE8eMeCHV36e2YmjGZKoORD1wJpwJorLqwSJ4DSRkF7dG0N5gi4WNQ700HbdmG886JZ4AHgxyA8chtpwjpLmvJIbI79zcFADHUxlMtsbWBmzmXw5RlRQsWMBynQp6kduq5uKPQowSHR7X5UQFfhG6BgeIK2o0QWIUU5tcCS1Cd3QUcZT3lzas8l/k6tP/Ig3IB+HffDa9KjFRkzBkvuuA7qsd5RR9SoWIyZTY9mxfOu69RgccXxxb
    USERNAME: AgC5gxBLMof4XNAsaY5bxlH8tZwhh0XImX2B8vxdjCR77fNZ2ThuWWWxIpvOzW+zHFbm8EqsrmIDUawa/HJpWzLlZUEiHuaydlGoi5yGoSZuqKd7k3UuU7dkl1TrCiyMSWdgAvJdnHqs3/DnvcC5Yg9i6fWZvtC4uv2eKX8lGPNDUHh9L4JQ6+5kHwssP6Q/DCqWRvNotlO3osl4eqqaiKCmk26N4MUkIX4PCGDby1xtg55nikmhDZxZjH9qPa49imthwc6eQ0D3sAq4d6F883q3qJC/RfgJMG1Mwra+mWnaatoAlsD14b+hnqOfweFsHdlkzT2qr5Cny8o8EqNuqqH3IG9psB+m25QReuwNmNeAecUPHFKjVVeKBcTqKQrQ8Z3iWYWdOHzQd+Cu9Ug4sjHW1wWc/z590bYb3+fnU4xBEsAFF2EwU8EX54aWJCnoksdHouyn5S2XiPR/rrX9NiJtts0pKPUQVoq5KSeABZBINr8uBREGQ5LKSzI12HcXqZx4YheeSs012NQ80hOQtukJqES4w6RTsjHRZacMjViHBJU5GgoJHCr0yqCe0Rzn4EYmtig56DWORk9WuBK5NeWeuiYHsM50fzy1JBriMpOLNIV3U4MHeYMKqxax9MbG/vRmkA50Mn3LLHnxNawPGHrvx5yfjFwRvXJ9WkBonzpIU8tKctgKUF8xIoJUWbTWci8WfBsqBRL5fvVejlJF
  template:
    metadata:
      name: mirror-garage-secret
      namespace: misc
