apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane
data:
  config.yaml: |
    server:
      host: 0.0.0.0
      port: 3000
      base_url: {{ .Values.headplane.config.url }}
      cookie_secret_path: /var/secrets/headplane/server/cookie-secret
      cookie_secure: true
    headscale:
      url: http://127.0.0.1:8080
      public_url: {{ .Values.headscale.config.url }}
      config_path: /etc/headscale/config.yaml
      config_strict: true
    integration:
      kubernetes:
        enabled: true
        validate_manifest: true
        pod_name: replaced-by-environment-variable
    oidc:
      issuer: {{ .Values.headplane.config.oidc.issuerUrl }}
      client_id: {{ .Values.headplane.config.oidc.clientId }}
      client_secret_path: /var/secrets/headplane/oidc/client-secret
      disable_api_key_login: {{ .Values.headplane.config.oidc.disableApiKeyLogin }}
      token_endpoint_auth_method: {{ .Values.headplane.config.oidc.tokenEndpointAuthMethod }}
      headscale_api_key_path: /var/secrets/headplane/headscale/api-key
      redirect_uri: {{ .Values.headplane.config.url }}/oidc/callback
      use_pkce: true
