apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name "{{ .Chart.Name }}"
  labels: &labels
    app.kubernetes.io/name: *name
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
  template:
    metadata:
      labels: *labels
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: *name
          image: favonia/cloudflare-ddns:{{ .Chart.Version }}
          env:
          - name: DOMAINS
            value: "{{ .Values.domain }}"
          - name: IP6_PROVIDER
            value: none
          - name: CLOUDFLARE_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: cloudflare-api-token
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ALL]
