---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cloudflare-ddns
spec:
  encryptedData:
    cloudflare-api-token: AgB0wzclTKenGZz/JqgNk5IREZuYDn7xlXI6kpmy9on7JVtIIkiosvQLDB8bvu/4V1YOijkp3Av1ktZVkS/YWO9DAVwNlPJSj9LsKzNPHZgGX0TU8EejsR66rE42qsMDkktJzG4zYwZwa8pG1htC5jOxhPOuh5YeOklr/BsOPX0tgOyRm9Mxt4YJFmqlQnOuJSLnGcH4QiJLgqvBie+6d8A3bRtuwZ8Yvrn26ipxO7fsRAQPoB5xRzAXygFXJubzPXjgZJkn904sYs9WUD8aCXtAZ7otnQzbKWDaVOCuaoIX93kulRwxO91RwdsaOFoUEETinRjjmgV0c+qFlYslBmhmtRFw6MHxQ18TtlVzJzQOCsmVDo21YWv/2uTtdHuJd4wjjRJZS+hQm+G2Ms0aKZTZ8hgE+wQLjqgGgAS0QY8G5K/csD2MUUVgJ7e0+l6squvYu3uXolE2P6AkkzXQ1lWO52GDqmLyz2in1qULZc1y3LM38i+q+zRccJzOKXv0k/dIpDGNUzIKCYMfZZBB+esaj8YUGvMFqxrCUaCW2IbiOKqBy/QKEJd8Tkkgev1oeC+X1WmRwwloseZh/Nsuo/lX/Q96OyxfAgyhDWu77byV4vaAlUvqPGljUTpHfXztnAOn0qSvP0QJZhInIxfu0/zL76ZsRu69gDA3WThEOE0o8vz5nBVS2izLMpa7mtp3ZqpRjyLqu/aUsR9rr+4v3h7uTBBvT3B2/2u/SxYerpZZEqTa+figXTmi
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cloudflare-ddns
