apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoolman
  labels:
    {{- include "spoolman.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "spoolman.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "spoolman.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: spoolman
          image: "ghcr.io/donkie/spoolman:{{ .Chart.AppVersion }}"
          env:
          - name: SPOOLMAN_CORS_ORIGIN
            value: http://192.168.2.42,http://voron.home.arpa
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /home/app/.local/share/spoolman
              name: spoolman-data
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ALL]
      volumes:
      - name: spoolman-data
        persistentVolumeClaim:
          claimName: spoolman-data
