---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-key
  namespace: traefik
spec:
  encryptedData:
    bouncer_key_traefik: AgCeLhgCV5+aTwIQFW0JtbLcNLd/ahHZbPzclzl3ToiRDqJJxpRiwdyBh72OLZHO2FT8NitnCv7EjFKNWjcRdS+BTElBiBW8NbmehoTIk6btl5kMRo+i/e98e2PJ6xH5jHA601dBF3gPxcp07XZleJMjE8Q+jRQ2Rnp+XlXDcy9V+C8q3xwhUn9aS0tqt2XmUcNT1bQl6pdvq8TYmspsoy/lOxtrufZPDLNyxDqOTtE1ZLkeu2Gq2wQlbcIkH6TRiD9K0O1cglQlrTAj+2Ni8DjR52G89qli47uF2NI/sRH072yWdH5ZRMczeDifcUJd1uTvnMAOQlO7qYRtLBmKAWvxUuwLA0pRDAnNPkqfwz+kkRx79FQfHTOlBGGfJeqECdlqvfrAoLj2DayPuMLPUPzhaP/U2Cax7mZF3yt78oM6ufqlvZXAXcJRmBhxNfTgGw9Te/69NURhbaKklQTJ216nVFy+irub5EcIO+xS469OwNERuy6R1AHihG9qvCy9Rr5NaIMABpZ48dAL8nJv0jyGsUHlnGLdtV8Ze3N75f6bBpaOpObARdsSx6XbDmFEYJcqHl0X80BQj+yqVWRtnGTQ8q7i40E8Pl4JU7UTEspctb+aQvL3hNZ69j3p0Rj111zHDbu8Oba6uYhFhX4i3FKOiDsjNUfI9PmM7BDiMHqi0YkkdcazFjsiJSM42T+3nu2H57+70cryQYSeatiMYH9wZ2FYNWztb96k0QRVbvCiAXJQJBRd1g74IDksvCQ9bps=
  template:
    metadata:
      name: crowdsec-key
      namespace: traefik
    type: Opaque
