grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - &host grafana.ncraig.dev
    tls:
    - secretName: grafana-ncraig-dev-cert
      hosts:
      - *host
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: prometheus
    datasources:
      enabled: true
      searchNamespace: prometheus
  envFromSecret: grafana-secret
  env:
    # prevents random admin password generation
    GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: true
  grafana.ini:
    server:
      root_url: https://grafana.ncraig.dev
    security:
      disable_initial_admin_creation: true
    auth:
      disable_login_form: true
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      name: Kanidm
      client_id: grafana
      client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
      scopes: openid profile email groups
      auth_url: https://sso.ncraig.dev/ui/oauth2
      token_url: https://sso.ncraig.dev/oauth2/token
      api_url: https://sso.ncraig.dev/oauth2/openid/grafana/userinfo
      use_pkce: true
      use_refresh_token: true
      allow_assign_grafana_admin: true
      role_attribute_path: "contains(groups[*], 'grafana_admins@sso.ncraig.dev') && 'Admin' || 'Viewer'"
