apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "whoami.fullname" . }}
  labels:
    {{- include "whoami.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-method: 'GET'
    nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local/api/authz/auth-request'
    nginx.ingress.kubernetes.io/auth-signin: 'https://auth.ncraig.dev?rm=$request_method'
    nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - whoami.ncraig.dev
      secretName: whoami-ncraig-dev-cert
  rules:
    - host: whoami.ncraig.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "whoami.fullname" $ }}
                port:
                  number: 80
