apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    theme: dark
    headerStyle: underlined
    statusStyle: dot
    layout:
      - Services:
      - User Management:
      - Cluster Management:
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn.svc.cluster.local
  custom.css: |
    .information-widget-kubernetes div :first-child {
      margin-left: 0px;
    }
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: ""
  widgets.yaml: |
    - kubernetes:
        nodes:
          show: false
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"

    - greeting:
        text_size: 2xl
        text: "◦"

    - kubernetes:
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
        cluster:
          show: false

    - greeting:
        text_size: 2xl
        text: "◦"

    - longhorn:
        expanded: true
        total: true
        nodes: false
        labels: true

    - greeting:
        text_size: 2xl
        text: "◦"

    - longhorn:
        expanded: true
        total: false
        nodes: true
        labels: true

    - datetime:
        text_size: 4xl
        format:
          timeStyle: short
  docker.yaml: ""
