---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-secret
  namespace: homepage
spec:
  encryptedData:
    argocd-token: AgBJ8cn9yOYyNvRh8zIsAKNzOQ3ymwb21bSWGqQOYQVYHFp+4MVV0nf67yQE/nI+e2pzfNN577gzCQi62UMWzhM4SGyC+FoI+iPHFcIJ73pP3CbDOPdqCSXqUmQciUWM7kcmdMLRwvTM9v4f2tR2AX51c4cDIijoHBVVeaVSvZmaOACoz8q0IBhuow3By8tuyYDQpu5S0SatTa2zHiJngox9GuIE0bG/c3YQju26psERWXQ4HixjY1mAwxfqTQp5XYmW9PTS8bEUfMwk0Pmn1tXNygQSu8wnskd9W0Q54EYSKDgDfBrLXmtEHA44r2uBjYwE0+nS7fllZKCOGIqTltBThh5rQyjyTldkXT9gbkGwnb9Fwwgyf3JzQQS50ayL5mkk1EK2p7GRGTENNLBuQ0qCD23kpfvNn8LQ3HDkRZtgpFAPHSaxHLGBqUxhsBpSFhXxvl6I6g/mnVwjlMW9I+lSLZOxwTyy266TXkYLsVJvkezU9zy5meLAD4Q3qDRXnt2dsH6tIcdmlUBMNaPK6yJUtepYpkrzuia8hpWTnK3y4RqNv/K9u2xrWchCQ5zImh0RCaXw1il2G12uGNfjrX9IA30VsndLEFuWysIad6clRgc98E/MklVKPOTS1PB5PTpPQ5lruwULHywPqlttlVI6SGFlpwlyCYPk5UeMzF+FA1URTLdiIQkagOm35Wj3Om/lsJsEIqDnF3q7MFuzyY+bqeRxs0IaDdmfQQcaNZPdbsReTvmbi4TIV/YNzKgN/YgqWe03AkQeg503MwuZ2qI3frpoJpjihwIKHaTZkhZ7/jtmRx6c18ckcQPWXfHCcp0nifZqi6ij5OeIlPU252BoHcgLdqYFVGgDldhK9T+jgiKd9PKgFlT+G37H8qqHwN3J0GJwhBRw7Q/BjXumtt+Cmb/WRooDFpbuReH/Ak41WjqjniaX/kAog9tN1rrn287A7aP7khJtnM4UrGZcoqrRX1tGgPMBPFpaVPZLo0Of47tOJkQk4q3rcodETwlB9jU=
  template:
    metadata:
      creationTimestamp: null
      name: homepage-secret
      namespace: homepage
