---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-secret
  namespace: homepage
spec:
  encryptedData:
    argocd-token: AgAtBlfCIB2p1fO0gIv0HmjI5GF538+bgzl2kjrX4F8zyuuDT1Rcdv8H3Hg8wqS4rYgIpTxhqdyJfIOUH17RKxkS+yVnXxZuPZW7/LEzCWPeWGI0U+HF7roHSx4w9C3k9WjgQcIdnEu+pampE05FWvhH3yWliGEso0cVSN5hxDAl1PQWmP+1zrMdO+qY8kuIBABScipw/aRJ6amLUE97ZQf81NHfO1nH4ZNZ6euKDeHk6NmQE4FN2iPgOiF0IveCjQ5Xpp8ZvJxOc/SqCNxqNh0+06ovHew/O4HEITWzIgu5wDvKZlLov8Kj1jP6gngc4PPcT0EtTsVi5oh5iCBl9MR3Rfptazb5c7yCjCKSXiFpqOTc0NEtIqpliQaKxGmLArOSsXoyKNsKYujp/s4f9o4wsM8TB51Lhb2nJXUiWpvNrjVNy8wFHPbhADOnXy1P1dgRjtjgANijq4GLdGnuNt/6A1cILlHzoZZR5HsUeTN9G7AirROqGWJBfoF52Md7g/vlFrTgrvtGNhm1Gyj+gjR2EviEWRVi5oCkBES/TlPwUA6e7yoXGH38qTn5kAsQJ19EuqZfaUIpKVpXHhCEkcSUN+Cr4bU/0EzqHRe1zgBGNv0GouuvhuUCo27mmxQ7dtv3QDBJDP7YczU53wIwdJghjHmwG2sqWg9aFx9iNn5SKgXVBgP3tAUAkrZFjwRgMELFm5Pj1fGYDklgN7BWDgqD93ea+pCMaUhDz9LYjoRh+OxqvJpmA2yYICAR9DUgaIG07ZzhOJtyU3o2yOVRhrNc0FX7/6jG8RGnFWtA+Q8Ea++JHs20E50dI07gSOxuJY/APkZnXpGtbs16oOavcXvjJMbxlm0k4xBhIkGDwnQL2hbq58CMHf4vbY05e+dyFjG9AnAjsoFhqSUGy+M195WwTNh4RUH09OVIz6U+M7gD46dPPQy5HFLwjKq2wdhMRMLHrSCdb0g6jtqxn3b8EtxPtwlF7s2EwGhMxiJ7M3WP4Bj5srw/W23zRhPMew+4bDQ=
  template:
    metadata:
      creationTimestamp: null
      name: homepage-secret
      namespace: homepage
