app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: traefik/whoami
            tag: latest

  service:
    main:
      ports:
        http:
          port: 80

  ingress:
    main:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-stg
      hosts:
        - host: &host debug.ncraig.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: whoami-cert
