concourse:
  postgresql:
    enabled: false
  secrets:
    create: false

  concourse:
    web:
      externalUrl: https://concourse.ncraig.dev
      localAuth:
        enabled: false
      postgres:
        host: postgres-rw.postgres.svc.cluster.local
        database: concourse
      auth:
        oidc:
          enabled: true
          displayname: Kanidm
          issuer: https://sso.ncraig.dev/oauth2/openid/concourse
          scope: email profile groups_name
          userNameKey: email
          groupsKey: groups
        mainTeam:
          oidc:
            group: concourse_admins

    worker:
      runtime: containerd
      containerd:
        seccompProfile: /seccomp/seccomp.json

  worker:
    additionalVolumeMounts:
    - name: seccomp
      mountPath: /seccomp
    additionalVolumes:
    - name: seccomp
      configMap:
        name: seccomp-profile

  web:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
      - concourse.ncraig.dev
      tls:
      - secretName: concourse-ncraig-dev-cert
        hosts:
        - concourse.ncraig.dev
