---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgCuRIDs//3q8HLcQNxP2Xo/c7HRDw+J0Eo1zwhZ8xpyQzkZMS2I/0f6OYfkF5d5+MwO+ANCv2CBJtEHEq6ApXh1y7E1PnqKQHYqaoekQDqz3CDs9huGNz0ICxiFGouSStQ/zsveeFZRbTijBakQf0LL1/8gPQyQxgNpuBed9a2kK9OyHXMo8Nx0i/uPdSSVhnl0s2zFOTXoHRh7ocUqHiTZXPXAbC2cr1SKqZ0FHGvtlK1hpWFUgBa3ZhTJzebzY8/Pf7Us36f0CpWdnRzrselgEto8rEnG9IuHaUydE1dBaK1VbBvABA+9jMagvNHLS5r/Lw8tM449Yy9/iSvzPUkltrCMROYOdkPj0JSdAvPtuZPi7/he6LRggWLcKJYEO0geiDl9cGc5eTAUPxnLV+d0Iz1/StM0I6p03cImgcM+oWFbUh6AKGdQsvOT+pvV0KlNSxWVKY7SjMhcqLyv75F9tV6NwKxV/mKIvXTOVxZUSkIMqX0j7Byllg+oPpfM8k/bY/5ztsKvAzEEK/e5PAV9kZ/YeJieyVceRipdlgpHVCsfzye4OwLif0ApGWOsA6v4Hpt/zS0HcxC+/C7S/TF28aC3KCR0uJ4ge/p5HkNluy7xq01UiPM4fA7RrwcfrMgodqZf6qb5+nA+puR8u5DtOjj3EtO2kfihEHn39HDg03iutXv8CSzIVsyHDdSHyIyR2Rd92YrRKyivSE4qrjZ1fYAgoXPjsCTaes8RzySDM4kb6Yx1JOM09Dv1JrEwdt7txLc32a/IAKhztNx9GIS8Yd2n1zH9TLk=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
