apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ncraig-dev-cert
spec:
  secretName: argocd-ncraig-dev-cert
  dnsNames:
    - "argocd.ncraig.dev"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
