authelia:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      enabled: true
      secret: auth-ncraig-dev-cert

  configMap:
    theme: dark
    default_2fa_method: totp
    password_policy:
      zxcvbn:
        enabled: true

    access_control:
      rules:
        - domain: longhorn.ncraig.dev
          policy: "two_factor"
          subject: "group:cluster_admin"
        - domain: whoami.ncraig.dev
          policy: "one_factor"
          subject: "group:whoami"

    identity_providers:
      oidc:
        enabled: true
        hmac_secret:
          secret_name: authelia-secret
          path: hmac-secret
        jwks:
          - algorithm: "RS256"
            use: "sig"
            key:
              path: /secrets/authelia-secret/jwks-key.pem
        cors:
          endpoints:
            - authorization
            - token
            - revocation
            - introspection
            - userinfo
          allowed_origins_from_client_redirect_uris: true
        clients:
          - client_name: "ArgoCD"
            client_id: hBv00QyLxfNEyJzRNcWEo0~SqdSCpyFRqhsuxw3HiYYTR2nhcD0diqQwI0U-ZbAI4fwMo3sG
            client_secret:
              path: /secrets/authelia-oidc-clients/argocd.clientsecret
            authorization_policy: two_factor
            require_pkce: false
            pkce_challenge_method: S256
            redirect_uris:
              - "https://argocd.ncraig.dev/auth/callback"
              - "https://argocd.ncraig.dev/pkce/verify"
            scopes:
              - openid
              - groups
              - email
              - profile
    session:
      cookies:
        - domain: ncraig.dev
          subdomain: auth
      redis:
        enabled: true
        deploy: true
        host: "authelia-redis-master.authelia.svc.cluster.local"
        password:
          secret_name: authelia-redis-secret
          path: redis-password
    authentication_backend:
      ldap:
        enabled: true
        implementation: lldap
        address: "ldap://lldap.lldap.svc.cluster.local"
        base_dn: "dc=ncraig,dc=dev"
        user: "uid=authelia,ou=people,dc=ncraig,dc=dev"
        password:
          secret_name: authelia-secret
          path: ldap-password
        additional_users_dn: "ou=people"
        users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
        additional_groups_dn: "ou=groups"
        groups_filter: "(&(member={dn})(objectClass=groupOfNames))"
    storage:
      encryption_key:
        secret_name: authelia-secret
        path: storage-encryption-key
      mysql:
        enabled: true
        deploy: true
        address: "tcp://authelia-mariadb.authelia.svc.cluster.local:3306"
        password:
          secret_name: authelia-secret
          path: mariadb-password
    notifier:
      smtp:
        enabled: true
        sender: "Authelia <no-reply@ncraig.dev>"
        address: "submission://mail.smtp2go.com:2525"
        username: "authelia.ncraig.dev"
        password:
          secret_name: authelia-secret
          path: smtp-password

  secret:
    additionalSecrets:
      authelia-secret: {}
      authelia-oidc-clients: {}
      authelia-redis-secret: {}

  mariadb:
    fullnameOverride: authelia-mariadb
    auth:
      existingSecret: authelia-mariadb-secret
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 1Gi

  redis:
    fullnameOverride: authelia-redis
    auth:
      existingSecret: "authelia-redis-secret"
      existingSecretPasswordKey: "redis-password"
