---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-secret
  namespace: headscale
spec:
  encryptedData:
    oidc_client_secret: AgA6CJhKj8WwLILO3wEKvxoS+w247itC7ZglZKO40yHgQJ56Cq+FAttZbyW1LpA7RBjedqGomVZg284bl9qGKLjKuDllzut3K5h3Ol6SvhYi6U9BYc7fl5WSJXBPxeN1je+XC7XE+EUVGcR1pr2b/NTqB4p36c2ROnuRswOjHI1Aci9PZKAUkBXSn3ALasPWdbJ1yUWHDVtUmcStD42ldqN+Tj4rsvK7T7n24Y7tQ/0Ki7JcTrLhXhGi01KbJ7Nw/+bCHAjWPpmSUBKXn3kTJAy2mmjXpQIF2KuBCeG8YZGDfCG2Iv1sOOyNpW7zIbUNXoIpBClHMC/YyozrMXZMuooShQ3GnTTil/thnZn4GxlzaW/vpEtVGinsaFp4KlH+7IdzLRtyJqip1OYtPIgR6VSAK2NqPJAnIVJIwImq7lEWL0TMdRhsRBUmQIQUFBRWd4O8kiokI5Ne1xvkUr+twWfIpJ0Oz3g7aNHzUXbhjJKVlEgJVsXi2QUBk8CJ2RzL3A08WmMLVCF6DMmu85K5TdMZzIOkxnsU7CQzG4P1VX84fU9cPd+EtVrge5WB0Rn21pWjF5LrduX/c6MTZGHs71v6nYx9yeQ5a1qS7rBtDRV2+JdfpX/DVEX/W+1EaCHmwOs0mSCZN3Rvbw+YaWLawBHPzsJk/Axnlgdq7CSGVaB/aJ8PHmkWMeEK0W6Bh5jEyHglMT2i/Ryd6qCJOKHSJax4cPcVLx2lgkVdVA+BiECJi2kOOXcb1pqmb9S/yOr4HNU=
  template:
    metadata:
      name: oidc-secret
      namespace: headscale
