---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: mariadb
spec:
  encryptedData:
    root-password: AgCpBtT3+VbYkYq6HizXezz7YlrUKOWebsASbPNrVX61SGXEGIP3sCqCAaf7yArKk2tIEhQB21n+KS4SWlF2nTuJSUeN4KE0eG+2zKYjW2OwQTXiEpMsnQQBhGiD1SUVAjui0hYXEQoFcRtvIID5g/XWsSxKce6YOAd0EfOWf2UqddZ6czxyskpJfDz4u7opF3zz+FTNgUpV2IDv+nnlVyIaX8fODii5aJ/r2h3v7HYSoUJ1Ljf8nCwqTsykP/q29NMAMoFoEEmCu/0+z4HmBiLFMDqAGme/ejjoAi+b29BLsWQDGrPsK4ET85q7jj1+qz+DQdaILsAYpAOl8fwcb77XZtXSWYIBUWOHtR+MecK4XaOMn0bz6pjTdw2JOwzRLTyBBSKPclknhCAkDc+P/0zo+lBr915j1W8O1TZP2iMUiIVEFJJJrlBZZQMv/OTcxzj09C48mi8dZkdx0iJasXd2Cxoe8XwemKueigBiNMRQeciK5ndXy/a4wH+N0HQ/Ff3C8+r+NHSpV3rdZE9idPGalZnrfFhlShPXOoq/YKy58fUykAyWlmXie0w+sREa8/1qp9Li1j5V+wVYfowb0EaeNwXPc0WlVMsuNImnXYVY4Ta6C1ayj+p+kA8zGfBRXZ47snZEQvsmXpaqLhRdHlbeeGqshcVoSXhDICcHLCOpJFojo7/LAZO97wS00mgEMJ42I7rtapjH0YbJ/SUwGAcYFRC5ovxPJs90Q5/o0TAUXpVUQ/kNoqhSC3Dk13jhV2M=
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-secret
      namespace: mariadb
