---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: mariadb
spec:
  encryptedData:
    replicationPassword: AgBqoNLsCV3bTrZiVE58LC6/jUbjVNuJ9hf8nLvSwsLYrMPylVf6mIOMTMaw8NDg89//+ixsR+j4f3diHqPLBMfIfgpWtZ67OY+la8CntBxiIiL5VKOO32CtLG2B0HdgjTlQJqn6wg1jovRuW2bFzUHyG6GVB2Jwh25zA/g8jEPpX27ac0emVmHjAXIzvfylutew0JQq222iKTIFO5z0y1aG61FFqu85/vLZD5CtIHSOrxRWsQALsTdUJdOctBfulnnvX3VKIpiWN/NFVov3iAfIaytigc92F/fancSXkG63njUt7TjHYOsO7popGt6IjZqSL4aqZlAKJ+MmPSSBx3iIlzzE69ZcRceWhUxnX9vO+hP+EGndGRrwLEsJbV3/LLP23Pr1qrcyRi3KFiKoWJNNn6BGwTsNPvZgUgbMPXqXn0iNEMOyrHbjW8fdzKq7tFaNvQLIXcD9bQ7VAyA4Z8Qd2d/qm55smQQvNGyChY1h8jx4+jI6sHFJDh+yAqE1XBlXZ2EoAeMIzZxm1HbXtX9rOcNdr0GuHh4uAhGyI5YSTDnsHjTgFN3co+SstZzg3VIUFiCMDwxiPDRekSUfVxfqfLyk7gLaALen9J9xoyGAW77wVBZZBKd93chsVP1R1wGNV6p6CyIGxLVtstNgzexZvCgNIz94jK9dVpIiW7gXSasxacsoi8hkGtwgx4Q1FCIJpC1cH63HvuCRWtkdgeSlusVuVA88oGDVx2rO2NRptA==
    rootPassword: AgBDXmU/6XiDqnKMdDLxAQqv/ZdzLrYTvaDOtyLo2KwQCKLVsyiOarIemrKapKKkBVvj9Nw8eAzLRZbpmhKvVOtWuY1QwYQTX4PMI0srG98zYPCCpXesVY1WUs+ZsfnwOkyFBSjaY1CHWgBcFP90F6Zx6t/7/tTh8tY5WOlnWKR+cvwRxD+85XnpZ/RiMYPZYSOp9LyIy8d4rYe5NFmJUEGUda1eJNZ66GeKpGYswOAup4/AstwTw4CUzGolldFd/GGvlp/Tf2qBnBqvzXzGG5OdQl30HKGb040xdRCJnmLVNs5Lu96zQ/CoOir/UW0HrzqzWzJlYZQuTFLS8+YYDm7Xz3QXrNjwEc52rsN0QE/yX7/RRpByP+rRJYuYB8PrjT+IlNoeycIE3N2lV4JWsrd4X4hebPlzN68m/pJGTxE5RjNR/1k93fJq9YdTSdv5jCP1j/rzq0hgCNS5wE9HwWC2gf9orAaypNRERGCt4wNdjjHPhV7tK1q/zLLIUD/7o7lYDZua1vKjxgo9IsqcX++RzMoH6VKlsYy37hHMil7UUJNim8S4UPQeRkrIZUTpPv07sGfhloWAZMFX86kIwkrgo1ZL+sSveeWZoQuxYSW0X99DYWf2HwtY3jq6gbRsOh2TfHE4rdbm1L0MvXnAMTBqsGFkVcHu2vwbF1qsaOOoZZAiMQF824qUk9buvXN8o3JEuEBPv9SLk8V9JHoShm9M0uuc+1c5j7Q8jId+D9uFHg==
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-secret
      namespace: mariadb
