---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: mariadb
spec:
  encryptedData:
    mariadb-replication-password: AgCGEtb9u3DDpZwjvqcoGT2ntEVsFkuQqQFwN2aLsVzUlo+hw2TxaGl84y7z2i+EvM6B4tFqyGsoH6YcLp+btRjgZfGKpEnSAfGF5Qfrf3rtFroExzTtcPa6PhJ2B/J7WTn2GqsIBNlnH95z34Qqaoff87sQJbwYoORT58hSrTJVx783Xvww7a7Q7q0g71fNLveObG7a3z8NYBCuIQb5PD5dMgss6+IVGz0oZJocBLfOvKf8TE0cola03gsUGLoj4sG3IhnOgcceoEAx7Rh4H+fiY/C1pRJ5oZitVsuU+p+K/xC6oOfbdTSDu/4SKf9DudXIdVjNrX+DE3kSmikiqfiz0lzSbQqNgoNXiFb811OngpPrS9pxU8JDNq1LtNJWjtNXwgosKOHck4akvJLtRi0eF5AZFLLx0m0UpFxLy1KYpXIJ/kkJ5QOwmWjHbIxFGxpZOBpDoVdeatHzLOtftK8S2Hpzcd6PWYhkzNA8rvRrRfpii8ZMVtIswxF92PnqsgrHrqeYbjcWRD+enzOrcUIAaxpD+75xqncfTTF591uWH4MAmaRYzSTV+ss+ZIW9aqn32IXxvysvFEYg9W0jlJZJ4XlMtby0rOtI/rk8YvkHVnJUy0x5+N/PhMaiWDbKpm1WQkZcTunzaYYwqFeMgLf3nvi/N+OlEaTBhNlTKtN4dITEiOrfRlGWURq8z2KVszHQiwblHPcUcf3t2zbNnXPtMLI6xY56sw5B2rnw1HoJOQ==
    mariadb-root-password: AgCJFcILy/JV9pw/ZiuWMTnqieXXFSIOoDUGDBh5vHz85hL2gOnkrjNuYwZ1acrD6Dj7/fj051BxZvkaqv/K2RxQ/R2AHothUAA4RW3NA6yOb5aCxrngjRjUmxuITIbYA97x3hWEbqUVo5y0LwOKB2NStnkxVrUjkZzE8riZJdJIRtblEmaIt7z8aRVwOvaYGq7CBUsQYanxUNXW2OhR+CH8lNi0RpwhQVR3T90c5dKChvzbV7z5UG6U8nXj/D/FyryvmbXrBrci0EHlX+zmx4E5Tc39Fn12bG6z56VCr9oG88L34O3AFzDVkN226TEdYOO6FUW7x4DM0q4xL1aRkCO6CqHFPILUeK910KNDsI+i/t53VHQsQPdzVcOaoqtUrjQbqJ45r7L4AmpjcewuI+Js49yLS9vRK399jzcBuhKIQovYtEVDxkTdnBZ12pWbi8wEP+iCCI8UfhYzxXTVDwPKYydTCfgRpAYEHefJVnjG7b/C1UujOMk0cTr0PVeNe+E1E74J5II42b6Jy0syYYuzroo123nTfMD1VGaYzcsHxjHyaSK8qkOEF9MPqRVEWQdQ0bhbcaaJgGVxB5ZY1Fa5lX9s71/A3jbhNAc4i/KTJV3EFKqsauquPj7IIo42eh/U85n3YYbhyUBErJzStjXWWRCPo7cDvvtNrija8HUDS5hTFHGNQADzNmRJu3ILuzcd8Yb1q+NTdiDlrzfDRD/EVvzpa/iYASqiNQ5Z4C1NnQ==
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-secret
      namespace: mariadb
