---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headplane-cookie-secret
  namespace: headplane
spec:
  encryptedData:
    cookie-secret: AgAIcNrrWQoeUYcrXJs2RSFVoAuXxnTs0e1OAit9Q4CPwx7FHI/7ZkQPM7qmLOAsTnXCWKlu1ndqLGLRDavhIEwc2pWc2nEIpeMqI9pPU9LVZEHqnhKdkpzVUHu9sgxyXUJUF4443F20iWn5+bAgPXV2vjE+FotJBLE0MpyMKpQfVOLd/OdRvuJdGtUbpxHQTHxbRg91BlG5qeQ1vA0QCS9kIu0VV7c4zgtx3H1LPzCLjXDvOEG1GUnu6vmLXMmYgvjGvmpTjn/VKStlSYaNyuVi2oqHSmUBwNxk+rIrzm/vurtlBOuN9+wgtqPFK2atadag7wLYTX1V11kBHkGswagp7oFDdyR8pNF/U1givLwBkxQdeGC+5XUhKNGn9RJB8w8oRBIL4rJiooEi4WEAkdoGV2/RgfWWdyLI3vogy/Ak9N8w9WT7RgGgiQG9z1RDccFXl9HrG5X2/w6PV84dBRRp2Ss2WiBWwZfZv62rikiMaSfX5SIN8eoBe6cWYtltbxXiSwwp4pEhc63m4QAOKeOqnIIbOU/bBO80JoC02dG7dKLkS91Ye9WJvZspsNiY7N0cTGlN1gPa7df4s/ZmJTH3tLNrWn7+YHNcglBueH2X7+DoqjESTmWkU5V358S5dQukz7tmI/cwAEG2yZ+8yFHSH6Xkiw3nYgmsvpfiu77FtiAWyZJ33PBp8C++IwxCpR/Oa9taEzWwd82aonXg35RMGrKZn7pFGQuw7FynIVbTdw==
  template:
    metadata:
      name: headplane-cookie-secret
      namespace: headplane
