---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headplane-oidc-client-secret
  namespace: headplane
spec:
  encryptedData:
    client-secret: AgBgGWOrl9l2PjCt8sLzAXig154gH+dV1oZ2gejyCp21amEydYnkIxCAwC4UuMuCxWBo5DWK9PV4kmoyTbOCPE/2smRwFh0P5woLIG5Vp0jVQ/Lns75lbggc6LtmvCgDrAO73941WcdtTWIuadx1lSnIwxWGuP+3FhZV4H2dlH2SwRI04MrLYciWxzT+7YhB0Wnyelu97t2d4/9n9qqWhskDFDO8LKb1VINmgfE86mHpdfiYR9raCTZ9dxddr3syRn7qGgXNnsSpWPiik9JnGWzGhWyAOXtIFq/dUMt4Fi+HC1F5wSIlXb5RrEoDIlM4CVhBCoYLbf2KQ/pplZANtvZUFdJUULnqie/E9nT1ozB4wbQVGGhDmnBTTXby6OAr0S96TORk/2LhR+YP8MxOVgsLAxjEgRbUk+K0P7cZ8YZqPkqjQ2uLQYXwgNf7MTrbCJoqx6i9DIfxxvkpRFN7X80x8DmXVSRTMeQZuwTPwJtg47oj2xEjYax3v2jfsIw5+Yud3VXe+tbFDWPhQm1eNHyOUgSw8JxXvVZBOCIy4/0EBNQbNAGmXZX6x+vrrWj/jYI2fWLvYS8jF2Wq4IL4zkGP62Jki9g8PmLtmkwCUI5cnXiDkjjRuAVH7p6+s4/WYt2GWok9Byi5HKRH0a77g1gYEJfiYyUxt/Zqtn6l+FOqly4XNGwM4sDSqDofiG5stw7jQa+pa1Z6d4i5wPyrSHSyML4TwexxQQsBYD35HV8psWwX6kw7dLRWpNl9fGL2gCE=
  template:
    metadata:
      name: headplane-oidc-client-secret
      namespace: headplane
