---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-oidc-client-secret
  namespace: headplane
spec:
  encryptedData:
    client-secret: AgCSROCRVkyzps6ZhwqAigt4QqkASfwfFbNT3j7YjAJYjy9y93WnUWtZNLiNJq+dE0Xe/AEkc5LMjwAWAJlTKxCOLzN+eidZdsdMocNRT2R2bt01Dn7Tx2sZEYJCDD9tqe9jK3X9q9X+9SH3GVFdXHzZzOZ860hJQROBF2MQLhjoNtxQrGSt5/XrLGtiV1xB+wgVFjN7jeasxxcoNBN7vW7M7Ylj5nAop6ztLXACkVwG3l5r/hXTTmMiFKGos0o97GUHNdzRtVg44PRw6dDHBLk8bJmf/97F+hC9Jxzuf0L+4o8oNdRIweXDMyW++3zsQWilQ1w202S7nBxS7xoCaDs5S0CRL2BSMG6WvitOgBPOYt67FEU4CtrP+S4VmuSaNJcUGndJO0yctKo4fCieklsL+YA3KME0LxIUcr5qmTIo4dUlTQ9uxiuuqPCW5uD7hVzcSVQ4eMyfKd8DYZ2/QeX44cBGPAto7jjh0ul667uwKAQyK4rj8htkVzakaVHQxSDWTnEV82iHk8DmlADdBKk5LWm7yQ6iQThNSgKm8w14ZynllaftGORFK781VdsMvyuEk0HmQrUyXhVHe6+A29pkhtFWy1FlF4WuEf0qMXHkvbd83umXENox5YmQx4qBTvqW1AuKye3c3VndFYDpqimr+lnc7rfbNlzNwUjTbvAC7cjygNJeBsV0oCBPN+CtdJTvKvVf3ZfzUgkSjb/2joQhEJFmhPVKWXAegdWhoex7jpaQH+T0j78zyJ7DXyjVu7U=
  template:
    metadata:
      name: headscale-oidc-client-secret
      namespace: headplane
