---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-rpc-secret
  namespace: garage
spec:
  encryptedData:
    rpcSecret: AgA/VNHs5lU0RceYBJMu27oPTSWpFMhWGhe9Dd2y4v2Jx74WPjdISR3w0hRyqshbSyezLR6HEgzzREyqazivFO5DUPzmhZObYKjWd2BK6XRSFG6iQgD7UdAjp9UWl16tPeRFA1140TfiH6yVIsgcS4Z3xHnZHI5bRXqXxNK0Q8NQXguUNSquPpKyEShtb3arsocOOtbXCDQSNXVRt4/IhQrekE1UAqHEMt+OP+DlEWv9tsOVlBg9E4lXtMCHoQtAICDbVaBCgzBm9rlDX/qXQa5bHQHsVVcICwRrwP8CWADtk7niEdLBPuHercch452kPzINyGnRuHvveq4Ef9xkldGxdMDpGHOh+C878RuyclVAVdMa/Uglj/dRkluFreVUOmcTTxtJlkMsUJKXU1kZlCJnX9XvPzs5D2zOHVjloNIFtrUkWLQ/V4XK5m4TH24YBIY0zRBeMmFNm6uE8CKOioqbxap2qn2xMg6k4IdGT9rTX/n4jrP+o0Q9teuovshUm6TjDMdiPcujBEZBAd14KBtl7GTDC9uk8CxWecP+QNVJhvGYsiDomgF+xes27OnbSRe7Dyu10wFabBOX3+gxAr4Xrisxints/5gYKGSHbRNij5ZAlp5cOnmH8yHCn7IQYo3Uyn8Hu3J/7Fy5H3EccUMC51Jw+bUvzDFwPjrS6JKd9llBqyyBbj46FxN+Y6GPmXS3+Vu600n4CQvhZNFxqPxIXhsZANClktItHS6F0L1YLE5gePYQp50sn2u3Q1c2kE/IHRmnHd4WhwkGMf6/Uzfy
  template:
    metadata:
      name: garage-rpc-secret
      namespace: garage
