when:
- event: push
  branch: ${CI_REPO_DEFAULT_BRANCH}
  path: containers/mirror-helm

steps:
- name: build-and-publish
  image: woodpeckerci/plugin-docker-buildx
  settings:
    repo: git.ncraig.dev/${CI_REPO_OWNER}/mirror-garage
    registry: git.ncraig.dev
    username: ${CI_REPO_OWNER}
    password:
      from_secret: docker_registry_password
    dockerfile: containers/mirror-helm/Dockerfile
    platforms: linux/amd64
    tag: latest
