apiVersion: v2
name: forgejo
version: "0.0.0"
dependencies:
- name: forgejo
  version: "13.0.0"
  repository: oci://code.forgejo.org/forgejo-helm
- name: valkey
  version: "3.0.22"
  repository: oci://registry-1.docker.io/bitnamicharts
